/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jflexnetbeans;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author stevi
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtf_cadena = new javax.swing.JTextField();
        jbtn_analizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxta_resul = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingresar archivo txt");

        jtxtf_cadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtf_cadenaActionPerformed(evt);
            }
        });

        jbtn_analizar.setText("Analizar Cadena");
        jbtn_analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_analizarActionPerformed(evt);
            }
        });

        jLabel2.setText("Resultado:");

        jtxta_resul.setColumns(20);
        jtxta_resul.setRows(5);
        jScrollPane1.setViewportView(jtxta_resul);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(57, 57, 57)
                        .addComponent(jtxtf_cadena))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_analizar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtf_cadena, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addComponent(jbtn_analizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtf_cadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtf_cadenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtf_cadenaActionPerformed

    private void jbtn_analizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_analizarActionPerformed
        // TODO add your handling code here:
        try{
            Analizar();
        }
        catch (IOException ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jbtn_analizarActionPerformed

        
    
    
    public void Analizar() throws IOException{
        
        
        
        String text = "";
        
        String archivo_entrada = jtxtf_cadena.getText(); 
        File archivo = new File(archivo_entrada);
        
        BufferedReader bf = new BufferedReader(new FileReader(archivo));
        String temp = "";
        String bfRead;
        while ((bfRead = bf.readLine())!= null) {            
            temp = temp + bfRead + "\r\n";
        }

        text = temp.toLowerCase();
        
//        String entradavacia = "";
//        
        File Entrada;
        Entrada = new File("cadena2.txt");
        FileWriter EntradaW = new FileWriter(Entrada);
        BufferedWriter EscrituraW = new BufferedWriter(EntradaW);
        PrintWriter FinalW = new PrintWriter(EscrituraW);
//        int var;
//        Reader readerminusculas = new BufferedReader(new FileReader(archivo_entrada));
//        var = readerminusculas.read();
//        while (var > 0) { 
//            entradavacia = entradavacia + readerminusculas.;
//            var = readerminusculas.read();
//            
//        }
       
        FinalW.write(text);
                EscrituraW.close();
                EntradaW.close();
        

        
//        PrintWriter writer;
//        try {
//            writer = new PrintWriter(archivo);
//            writer.print(jtxtf_cadena.getText());
//            writer.close();
//        } catch(FileNotFoundException ex) {
//            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);    
//        }
        
        File f;
        f = new File("errores.txt");
        FileWriter w = new FileWriter(f);
        BufferedWriter bw = new BufferedWriter(w);
        PrintWriter wr = new PrintWriter(bw);
        wr.write("ERRORES \r\n");
        
        File miniPHP;
        miniPHP = new File("miniPHP.out");
        FileWriter escritorphp = new FileWriter(miniPHP);
        BufferedWriter bufferedwriterphp = new BufferedWriter(escritorphp);
        PrintWriter printwriterphp = new PrintWriter(bufferedwriterphp);
        printwriterphp.write("MINIPHP \r\n");
               
        Reader reader = new BufferedReader(new FileReader("cadena2.txt"));
        
        Lexer lexer = new Lexer(reader);
        String resul = "";
        String error = "";
        int count = 1;
        while (true) {            
            Token token = lexer.yylex();
            if (token == null) {
                resul = resul + "\r\n" + "EOF";
                jtxta_resul.setText(resul);
                
                printwriterphp.write(resul);
                printwriterphp.close();
                bw.close();
                
                wr.write(error);
                wr.close();
                bw.close();
                return;
            }
            switch(token){
                case ERROR:
                    error = error + lexer.lexeme + "No reconocido en la linea " + count + "\r\n";
                    
                    
                    break;
                case BASE_DE_DATOS:
                    resul = resul + lexer.lexeme.toUpperCase() + "\r\n";
                    count = count +1;
                    break;
                default:
                    resul = resul + lexer.lexeme.toLowerCase() + "\r\n";
                    count = count +1;
                    
                    
            }
        
        
        
            
    }
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_analizar;
    private javax.swing.JTextArea jtxta_resul;
    private javax.swing.JTextField jtxtf_cadena;
    // End of variables declaration//GEN-END:variables
}
